Adding Divider
next-md/next-md pull request #1
Opened 2017-04-11 00:28 UTC by JacobPrice

2017-04-11 01:03 UTC, tuckerconnelly requested changes

2017-04-11 01:03 UTC, tuckerconnelly commented on src/components/Divider.js
> +  style: PropTypes.object,
Separate custom props (color) from regular react props (style) with a line-break--makes the component "interface" more clear.

2017-04-11 01:03 UTC, tuckerconnelly commented on src/components/Divider.js
> +      borderTopColor: 'rgba(0, 0, 0, .12)',
Color prop not doing anything :P try `color || 'rgba(0, 0, 0, 0.12)'`

Also might be able to fit whole style prop on one line.

2017-04-11 01:04 UTC, tuckerconnelly commented on src/components/Divider.js
> +    }}
Careful of default browser styles--might wanna go full `<style jsx />` on this bish

2017-04-14 15:58 UTC, tuckerconnelly requested changes

2017-04-14 15:58 UTC, tuckerconnelly commented on package.json
> +    "react": "^15.5.3",
Hadn't noticed this--should be a peer dep I think

2017-04-14 15:58 UTC, tuckerconnelly commented on src/components/Divider.js
> +  <hr style={{borderTopColor: color || 'rgba(0, 0, 0, 0.12)', ...style}} />
Nice! As long as it looks good 😎 

Maybe just remove the `()` for maximum minimalism?

2017-04-20 00:41 UTC, JacobPrice commented on src/components/Divider.js
> +  <hr style={{borderTopColor: color || 'rgba(0, 0, 0, 0.12)', ...style}} />
Prettier adds them 😭

2017-04-20 03:15 UTC, merged